### ISSUE TITLE
a few fixes

### ISSUE THREAD

**Issue by hatemhosny** [KonnorRogers/konnors-ninja-keys#17]
Thank you for pushing forward this great project.

I have found some issues and I think I found fixes for them:

- The `.breadcrumb:focus-visible` has a red background. I propose [this fix](https://github.com/KonnorRogers/konnors-ninja-keys/commit/525d90fc9c9e9037210e43b94e1385e573eb11b7).

![image](https://github.com/user-attachments/assets/a0a67d70-193f-40b8-b29f-b75549d47077)

- When `disableHotkeys` is enabled, the command menu becomes empty. I believe this option should just skip registering the keyboard shortcuts while keeping the UI. I suggest [this fix](https://github.com/KonnorRogers/konnors-ninja-keys/commit/27dfc7f1bd2b77017906cc0e68aec050c28eaddb).
- Items listed after an item with children aren't displayed (see https://github.com/ssleptsov/ninja-keys/issues/26)
  I applied [this fix](https://github.com/ssleptsov/ninja-keys/pull/30) ([converted to jsdoc](https://github.com/KonnorRogers/konnors-ninja-keys/commit/b57f2fd72f6bcbc7bec8a0bb8126c15b71bfcd39))

You can try it here: https://unpkg.com/@hatemhosny/ninja-keys@1.14.0/bundle/index.js

If you are interested, I can open a PR with any or all of these.
Thanks a lot for making this available.

**Comment by KonnorRogers** [comment]
Absolutely happy to look at a PR! I think that breadcrumb style was left over when I was trying to override some original behavior that wouldn't let you tab the breadcrumbs. But yes please,
More than happy to add these fixes.

**Comment by KonnorRogers** [comment]
Released in `v1.14.0`
